### ISSUE TITLE
Supabase in Production

### ISSUE THREAD

**Issue by Hannes1** [AronBe/supabase-talk#1]
Hi, have you tried making a production build with supabase, as I'm currently trying to make a production build but supabase queries not working, just stuck at await although it works in development. Any advice if you've had this problem would be apreciated

**Comment by AronBe** [comment]
@Hannes1 Hey, actually, I have never tried in production and not sure where could be an issue if it works in development. Is your key (env?) loaded correctly? 

Else, there is also `https://github.com/charpeni/react-native-url-polyfill` piece implemented

**Comment by Hannes1** [comment]
@AronBe Okay thanks for your time, and unfortunately yes the .env and pollyfill is correctly implemented, it's strange behavior because the authentication works but when querying user data the 'supabase await' is never resolved. 

And thanks for the example app with typescript👍
